apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: dcp

spec:
  type: ClusterIP

  selector:
    app: notification-service

  ports:
    - port: 4009
      targetPort: 4009