apiVersion: v1
kind: ResourceQuota

metadata:
  name: dcp-resource-quota
  namespace: dcp

spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi

    limits.cpu: "16"
    limits.memory: 16Gi

    pods: "50"

    configmaps: "20"

    secrets: "20"