syntax = "proto3";

package product;

service ProductService {
    rpc GetProductById(ProductRequest)
        returns (ProductResponse);

    rpc GetAllProducts(Empty)
        returns (ProductListResponse);
}

message Empty {}

message ProductRequest {
    string id = 1;
}

message ProductResponse {
    string id = 1;
    string name = 2;
    string description = 3;
    double price = 4;
    bool isActive = 5;
    string categoryId = 6;
    string categoryName = 7;
    string createdAt = 8;
    string updatedAt = 9;
}

message ProductListResponse {
    repeated ProductResponse products = 1;
}