apiVersion: v1
kind: Service

metadata:
  name: grafana-headless
  namespace: monitoring

spec:
  clusterIP: None

  selector:
    app: grafana

  ports:
    - name: http
      port: 3000
      targetPort: 3000