apiVersion: v1
kind: ConfigMap

metadata:
  name: shared-config
  namespace: dcp

data:
  NODE_ENV: development

  API_GATEWAY_URL: http://api-gateway-service:3000
  GRAPHQL_GATEWAY_URL: http://graphql-gateway-service:4010

  USER_SERVICE_URL: http://user-service:4001/api/v1
  PRODUCT_SERVICE_URL: http://product-service:4002/api/v1
  CART_SERVICE_URL: http://cart-service:4003/api/v1
  ORDER_SERVICE_URL: http://order-service:4004/api/v1
  PAYMENT_SERVICE_URL: http://payment-service:4005/api/v1
  INVENTORY_SERVICE_URL: http://inventory-service:4006/api/v1
  SEARCH_SERVICE_URL: http://search-service:4007/api/v1
  ANALYTICS_SERVICE_URL: http://analytics-service:4008/api/v1
  NOTIFICATION_SERVICE_URL: http://notification-service:4009

  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  REDIS_URL: redis://redis:6379
  ELASTICSEARCH_URL: http://elasticsearch:9200
  PROMETHEUS_URL: http://prometheus:9090
  GRAFANA_URL: http://grafana:3000