apiVersion: v1
kind: ConfigMap

metadata:
  name: shared-config
  namespace: dcp

data:
  NODE_ENV: development

  API_GATEWAY_URL: http://api-gateway-service:3000
  GRAPHQL_GATEWAY_URL: http://graphql-gateway-service:4010

  USER_SERVICE_URL: http://user-service:4001
  PRODUCT_SERVICE_URL: http://product-service:4002
  CART_SERVICE_URL: http://cart-service:4003
  ORDER_SERVICE_URL: http://order-service:4004
  PAYMENT_SERVICE_URL: http://payment-service:4005
  INVENTORY_SERVICE_URL: http://inventory-service:4006
  SEARCH_SERVICE_URL: http://search-service:4007
  ANALYTICS_SERVICE_URL: http://analytics-service:4008
  NOTIFICATION_SERVICE_URL: http://notification-service:4009

  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  REDIS_URL: redis://redis:6379
  ELASTICSEARCH_URL: http://elasticsearch:9200
  PROMETHEUS_URL: http://prometheus:9090
  GRAFANA_URL: http://grafana:3000