apiVersion: v1
kind: Service

metadata:
  name: graphql-gateway-service
  namespace: dcp

spec:
  type: ClusterIP

  selector:
    app: graphql-gateway

  ports:
    - port: 4010
      targetPort: 4010